package phd.cml.fireworks;

/**
 * Created by Clemencio Morales Lucas.
 */
public interface BenchmarkFunctionConstants {

    int SQUARE_VALUE = 2;
    int ONE_HUNDRED = 100;
    double DOUBLE_SQUARE_VALUE = 2.0;
    String INVALID_FUNCTION_INDEX = "invalid function index ";
    int ERROR_CODE_STATUS = -1;
    double DOUBLE_IDENTITY_VALUE = 1.0;
    int GRIEWANKS_CONSTANT_DIVIDER = 4000;
    int IDENTITY_VALUE = 1;
    int RASTRIGIN_UPPER_BOUND = 10;
    int RASTRIGIN_LOWER_BOUND = -10;
    int ACKLEY_FUNCTION_UPPER_BOUND = 20;
    int ACKLEY_FUNCTION_LOWER_BOUND = -20;
    double ACKLEY_FUNCTION_NEGATIVE_MULTIPLIER = -0.2;
    double PENALIZED_BENCHMARK_FUNCTION_MULTIPLIER = 0.1;
    int PENALIZED_BENCHMARK_FUNCTION_SIN_VALUE = 3;
    double MIU_BOUND = 5.0;
    double MIU_MULTIPLIER_FACTOR = 100.0;
    double MIU_POWER = 4.0;
    double SIX_HUMP_CAMEL_BACK_FUNCTION_CONST = 2.1;
    int SIX_HUMP_CAMEL_BACK_FOUR = 4;
    double SIX_HUMP_CAMEL_BACK_FOUR_DOUBLE = 4.0;
    double SIX_HUMP_CAMEL_BACK_SIX = 6.0;
    double SIX_HUMP_CAMEL_BACK_THREE_DOUBLE = 3.0;
    int GOLDSTEIN_NINETEEN = 19;
    int GOLDSTEIN_FOURTEEN = 14;
    int GOLDSTEIN_THREE = 3;
    int GOLDSTEIN_SIX = 6;
    int GOLDSTEIN_THIRTY = 30;
    int GOLDSTEIN_FOURTYEIGHT = 48;
    int GOLDSTEIN_TWELVE = 12;
    int GOLDSTEIN_EIGHTEEN = 18;
    int GOLDSTEIN_THIRTYTWO = 32;
    int GOLDSTEIN_THIRTYSIX = 36;
    int GOLDSTEIN_TWENTYSEVEN = 27;
    double SCHAFFER_HALF = 0.5;
    double SCHAFFER_THOUSANDTH = 0.001;
}
